"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const Cat_1 = require("./Cat");
const Dog_1 = require("./Dog");
let dog = new Dog_1.Dog("GoatKyar");
let cat = new Cat_1.Cat("MeeNyaung");
dog.latpay;
console.log(dog.getInfo());
console.log();
console.log(cat.getInfo());
